vich_uploader:
    db_driver: orm

    mappings:
        icon_images:
            uri_prefix: /uploads/icons
            upload_destination: '%kernel.project_dir%/public/uploads/icons'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            # Suppression gérée manuellement par ImageUploadListener (PRE_UPLOAD)
            # Car nous modifions le nom du fichier (conversion WebP)
            delete_on_update: false
            delete_on_remove: true
